name: Publish

on:
  release:
    types:
      - created

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Poetry
        run: pip install --no-input poetry

      - name: Publish package
        run: |
          poetry config http-basic.pypi "__token__" "${{ secrets.POETRY_PYPI_TOKEN_PYPI }}"
          poetry publish --build
